/**
 * Export format implementations and step formatting helpers.
 */

/** Get human-readable step title */
export function getStepTitle(step: any): string {
  const titles: Record<string, string> = {
    goto: 'Navigate to URL',
    click: 'Click Element',
    fill: 'Fill Input',
    waitFor: 'Wait for Element',
    screenshot: 'Take Screenshot',
    caption: 'Show Caption',
    pause: 'Pause',
    scroll: 'Scroll',
    highlight: 'Highlight Element',
    assertText: 'Assert Text',
    assertUrl: 'Assert URL',
    executeScript: 'Execute Script',
  };
  return titles[step.type] || step.type;
}

/** Get step details as text */
export function getStepDetails(step: any): string | null {
  const details: string[] = [];
  if (step.url) details.push(`**URL**: ${step.url}`);
  if (step.selector) details.push(`**Selector**: \`${step.selector}\``);
  if (step.text) details.push(`**Text**: ${step.text}`);
  if (step.value) details.push(`**Value**: ${step.value}`);
  if (step.timeout) details.push(`**Timeout**: ${step.timeout}ms`);
  if (step.ms) details.push(`**Duration**: ${step.ms}ms`);
  return details.length > 0 ? details.join('\n') : null;
}

/** Get step details as HTML */
export function getStepDetailsHtml(step: any): string {
  const details = getStepDetails(step);
  if (!details) return '';
  const html = details
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(
      /`(.*?)`/g,
      '<code style="background: #e5e7eb; padding: 2px 6px; border-radius: 3px;">$1</code>'
    )
    .replace(/\n/g, '<br>');
  return `<div class="step-details">${html}</div>`;
}

/** Export flow as Markdown documentation */
export function exportAsMarkdown(flow: any): string {
  const lines: string[] = [];
  lines.push(`# ${flow.name}`);
  lines.push('');
  if (flow.description) {
    lines.push(flow.description);
    lines.push('');
  }
  lines.push('## Flow Steps');
  lines.push('');

  const steps = flow.definition?.steps || [];
  steps.forEach((step: any, index: number) => {
    lines.push(`### Step ${index + 1}: ${getStepTitle(step)}`);
    lines.push('');
    if (step.narrate) {
      lines.push(`**Narration**: ${step.narrate}`);
      lines.push('');
    }
    const details = getStepDetails(step);
    if (details) {
      lines.push(details);
      lines.push('');
    }
  });

  lines.push('---');
  lines.push(`*Generated by CodeRail Flow*`);
  return lines.join('\n');
}

/** Export flow as HTML documentation */
export function exportAsHtml(flow: any): string {
  const steps = flow.definition?.steps || [];
  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${flow.name} - CodeRail Flow</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; line-height: 1.6; color: #333; }
    h1 { color: #2563eb; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px; }
    h2 { color: #4b5563; margin-top: 30px; }
    .step { background: #f9fafb; border-left: 4px solid #3b82f6; padding: 16px; margin: 16px 0; border-radius: 4px; }
    .step-number { font-weight: bold; color: #3b82f6; font-size: 14px; text-transform: uppercase; margin-bottom: 8px; }
    .narration { font-style: italic; color: #6b7280; margin: 8px 0; }
    .step-details { font-size: 14px; margin-top: 8px; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; text-align: center; color: #6b7280; font-size: 14px; }
  </style>
</head>
<body>
  <h1>${flow.name}</h1>
  ${flow.description ? `<p>${flow.description}</p>` : ''}
  <h2>Flow Steps</h2>
  ${steps
    .map(
      (step: any, index: number) => `
    <div class="step">
      <div class="step-number">Step ${index + 1}: ${getStepTitle(step)}</div>
      ${step.narrate ? `<p class="narration">${step.narrate}</p>` : ''}
      ${getStepDetailsHtml(step)}
    </div>
  `
    )
    .join('')}
  <div class="footer">Generated by <a href="https://coderail.app">CodeRail Flow</a></div>
</body>
</html>`.trim();
}

/** Export flow as YAML */
export function exportAsYaml(flow: any): string {
  const lines: string[] = [];
  lines.push(`name: ${flow.name}`);
  if (flow.description) lines.push(`description: ${flow.description}`);
  lines.push('definition:');
  lines.push('  params:');

  const params = flow.definition?.params || [];
  if (params.length === 0) {
    lines.push('    []');
  } else {
    params.forEach((param: any) => {
      lines.push(`    - name: ${param.name}`);
      lines.push(`      type: ${param.type}`);
      lines.push(`      required: ${param.required}`);
    });
  }

  lines.push('  steps:');
  const steps = flow.definition?.steps || [];
  steps.forEach((step: any) => {
    lines.push(`    - type: ${step.type}`);
    Object.keys(step).forEach((key) => {
      if (key !== 'type' && key !== 'narrate') {
        const value = step[key];
        if (typeof value === 'string') lines.push(`      ${key}: "${value}"`);
        else if (typeof value === 'boolean') lines.push(`      ${key}: ${value}`);
        else if (typeof value === 'number') lines.push(`      ${key}: ${value}`);
      }
    });
  });

  return lines.join('\n');
}
