/**
 * Flow Export Utilities
 *
 * Export flows in various formats for documentation, sharing, and archiving.
 */

import type { Flow } from '@coderail-flow/dsl';

export type ExportFormat = 'json' | 'markdown' | 'html' | 'yaml';

/**
 * Export flow to specified format
 */
export function exportFlow(flow: Flow, format: ExportFormat): string {
  switch (format) {
    case 'json':
      return exportAsJson(flow);
    case 'markdown':
      return exportAsMarkdown(flow);
    case 'html':
      return exportAsHtml(flow);
    case 'yaml':
      return exportAsYaml(flow);
    default:
      throw new Error(`Unsupported export format: ${format}`);
  }
}

/**
 * Export flow as JSON
 */
function exportAsJson(flow: Flow): string {
  return JSON.stringify(flow, null, 2);
}

/**
 * Export flow as Markdown documentation
 */
function exportAsMarkdown(flow: Flow): string {
  const lines: string[] = [];

  lines.push(`# ${flow.name}`);
  lines.push('');

  if (flow.description) {
    lines.push(flow.description);
    lines.push('');
  }

  lines.push('## Flow Steps');
  lines.push('');

  const steps = flow.definition?.steps || [];
  steps.forEach((step, index) => {
    lines.push(`### Step ${index + 1}: ${getStepTitle(step)}`);
    lines.push('');

    if (step.narrate) {
      lines.push(`**Narration**: ${step.narrate}`);
      lines.push('');
    }

    const details = getStepDetails(step);
    if (details) {
      lines.push(details);
      lines.push('');
    }
  });

  lines.push('---');
  lines.push(`*Generated by CodeRail Flow*`);

  return lines.join('\n');
}

/**
 * Export flow as HTML documentation
 */
function exportAsHtml(flow: Flow): string {
  const steps = flow.definition?.steps || [];

  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${flow.name} - CodeRail Flow</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      max-width: 800px;
      margin: 40px auto;
      padding: 20px;
      line-height: 1.6;
      color: #333;
    }
    h1 { color: #2563eb; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px; }
    h2 { color: #4b5563; margin-top: 30px; }
    .step {
      background: #f9fafb;
      border-left: 4px solid #3b82f6;
      padding: 16px;
      margin: 16px 0;
      border-radius: 4px;
    }
    .step-number {
      font-weight: bold;
      color: #3b82f6;
      font-size: 14px;
      text-transform: uppercase;
      margin-bottom: 8px;
    }
    .narration {
      font-style: italic;
      color: #6b7280;
      margin: 8px 0;
    }
    .step-details {
      font-size: 14px;
      margin-top: 8px;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
      text-align: center;
      color: #6b7280;
      font-size: 14px;
    }
  </style>
</head>
<body>
  <h1>${flow.name}</h1>
  ${flow.description ? `<p>${flow.description}</p>` : ''}

  <h2>Flow Steps</h2>

  ${steps.map((step, index) => `
    <div class="step">
      <div class="step-number">Step ${index + 1}: ${getStepTitle(step)}</div>
      ${step.narrate ? `<p class="narration">${step.narrate}</p>` : ''}
      ${getStepDetailsHtml(step)}
    </div>
  `).join('')}

  <div class="footer">
    Generated by <a href="https://coderail.app">CodeRail Flow</a>
  </div>
</body>
</html>
  `.trim();

  return html;
}

/**
 * Export flow as YAML
 */
function exportAsYaml(flow: Flow): string {
  const lines: string[] = [];

  lines.push(`name: ${flow.name}`);
  if (flow.description) {
    lines.push(`description: ${flow.description}`);
  }
  lines.push('definition:');
  lines.push('  params:');

  const params = flow.definition?.params || [];
  if (params.length === 0) {
    lines.push('    []');
  } else {
    params.forEach((param) => {
      lines.push(`    - name: ${param.name}`);
      lines.push(`      type: ${param.type}`);
      lines.push(`      required: ${param.required}`);
    });
  }

  lines.push('  steps:');

  const steps = flow.definition?.steps || [];
  steps.forEach((step) => {
    lines.push(`    - type: ${step.type}`);
    Object.keys(step).forEach((key) => {
      if (key !== 'type' && key !== 'narrate') {
        const value = (step as any)[key];
        if (typeof value === 'string') {
          lines.push(`      ${key}: "${value}"`);
        } else if (typeof value === 'boolean') {
          lines.push(`      ${key}: ${value}`);
        } else if (typeof value === 'number') {
          lines.push(`      ${key}: ${value}`);
        }
      }
    });
  });

  return lines.join('\n');
}

/**
 * Get human-readable step title
 */
function getStepTitle(step: any): string {
  const titles: Record<string, string> = {
    goto: 'Navigate to URL',
    click: 'Click Element',
    fill: 'Fill Input',
    waitFor: 'Wait for Element',
    screenshot: 'Take Screenshot',
    caption: 'Show Caption',
    pause: 'Pause',
    scroll: 'Scroll',
    highlight: 'Highlight Element',
    assertText: 'Assert Text',
    assertUrl: 'Assert URL',
    executeScript: 'Execute Script',
  };

  return titles[step.type] || step.type;
}

/**
 * Get step details as text
 */
function getStepDetails(step: any): string | null {
  const details: string[] = [];

  if (step.url) {
    details.push(`**URL**: ${step.url}`);
  }

  if (step.selector) {
    details.push(`**Selector**: \`${step.selector}\``);
  }

  if (step.text) {
    details.push(`**Text**: ${step.text}`);
  }

  if (step.value) {
    details.push(`**Value**: ${step.value}`);
  }

  if (step.timeout) {
    details.push(`**Timeout**: ${step.timeout}ms`);
  }

  if (step.ms) {
    details.push(`**Duration**: ${step.ms}ms`);
  }

  return details.length > 0 ? details.join('\n') : null;
}

/**
 * Get step details as HTML
 */
function getStepDetailsHtml(step: any): string {
  const details = getStepDetails(step);
  if (!details) return '';

  const html = details
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/`(.*?)`/g, '<code style="background: #e5e7eb; padding: 2px 6px; border-radius: 3px;">$1</code>')
    .replace(/\n/g, '<br>');

  return `<div class="step-details">${html}</div>`;
}

/**
 * Download exported flow
 */
export function downloadExportedFlow(content: string, filename: string, format: ExportFormat) {
  const mimeTypes: Record<ExportFormat, string> = {
    json: 'application/json',
    markdown: 'text/markdown',
    html: 'text/html',
    yaml: 'text/yaml',
  };

  const extension: Record<ExportFormat, string> = {
    json: 'json',
    markdown: 'md',
    html: 'html',
    yaml: 'yml',
  };

  const blob = new Blob([content], { type: mimeTypes[format] });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${filename}.${extension[format]}`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
