import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Cookie, Plus, X } from 'lucide-react';
import { useCookieProfiles } from './useCookieProfiles';
import { CookieProfileList } from './CookieProfileList';
import { ProfileEditor } from './ProfileEditor';
export function CookieManager({ projectId, onClose }) {
    const cm = useCookieProfiles(projectId);
    return (_jsxs("div", { className: "inspector-layout", children: [_jsx("div", { className: "cookie-sidebar", children: _jsxs("div", { className: "card", children: [_jsxs("div", { className: "panel-header", children: [_jsxs("div", { className: "h2", children: [_jsx(Cookie, { size: 18, style: { marginRight: 8 } }), "Auth Profiles"] }), _jsx("button", { className: "btn btn-icon", onClick: onClose, "aria-label": "Close auth profiles", children: _jsx(X, { size: 16 }) })] }), _jsxs("div", { className: "field-group", children: [_jsx("input", { className: "input mb-8", placeholder: "New profile name", value: cm.newProfileName, onChange: (e) => cm.setNewProfileName(e.target.value) }), _jsxs("button", { className: "btn w-full", onClick: cm.createProfile, disabled: cm.saving, "aria-label": "Create new auth profile", children: [_jsx(Plus, { size: 16, "aria-hidden": "true" }), " Create Profile"] })] }), cm.error && _jsx("div", { className: "error-banner error-banner--small mb-12", children: cm.error }), _jsx(CookieProfileList, { profiles: cm.profiles, selectedId: cm.selectedProfile?.id, onSelect: (p) => cm.setSelectedProfile(p), onDelete: (id) => cm.deleteProfile(id) })] }) }), _jsx("div", { className: "card panel-grow", children: cm.selectedProfile ? (_jsx(ProfileEditor, { cm: cm })) : (_jsx("div", { className: "cookie-placeholder", children: _jsxs("div", { className: "cookie-placeholder-inner", children: [_jsx(Cookie, { size: 64, className: "cookie-placeholder-icon" }), _jsx("div", { children: "Select or create an auth profile to manage cookies" }), _jsx("div", { className: "small mt-8", children: "Auth profiles store cookies for running flows against authenticated apps" })] }) })) })] }));
}
