import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect } from 'react';
import { Save, X } from 'lucide-react';
export function CookieEditorModal({ cookie, showValues, onSave, onClose, onChange, }) {
    useEffect(() => {
        const handleKey = (e) => {
            if (e.key === 'Escape')
                onClose();
        };
        document.addEventListener('keydown', handleKey);
        return () => document.removeEventListener('keydown', handleKey);
    }, [onClose]);
    return (_jsx("div", { role: "dialog", "aria-modal": "true", "aria-labelledby": "cookie-editor-title", onClick: onClose, className: "cookie-modal-backdrop", children: _jsxs("div", { className: "card cookie-modal-body", onClick: (e) => e.stopPropagation(), children: [_jsxs("div", { className: "cookie-modal-header", children: [_jsx("div", { id: "cookie-editor-title", className: "h2", children: "Edit Cookie" }), _jsx("button", { className: "btn btn-icon", onClick: onClose, "aria-label": "Close dialog", children: _jsx(X, { size: 16 }) })] }), _jsxs("div", { className: "cookie-modal-fields", children: [_jsxs("div", { children: [_jsx("label", { htmlFor: "cookie-name", className: "small field-label", children: "Name *" }), _jsx("input", { id: "cookie-name", className: "input", value: cookie.name, onChange: (e) => onChange({ ...cookie, name: e.target.value }) })] }), _jsxs("div", { children: [_jsx("label", { htmlFor: "cookie-value", className: "small field-label", children: "Value *" }), _jsx("input", { id: "cookie-value", className: "input", type: showValues ? 'text' : 'password', value: cookie.value, onChange: (e) => onChange({ ...cookie, value: e.target.value }) })] }), _jsxs("div", { children: [_jsx("label", { htmlFor: "cookie-domain", className: "small field-label", children: "Domain *" }), _jsx("input", { id: "cookie-domain", className: "input", placeholder: ".example.com", value: cookie.domain, onChange: (e) => onChange({ ...cookie, domain: e.target.value }) })] }), _jsxs("div", { children: [_jsx("label", { htmlFor: "cookie-path", className: "small field-label", children: "Path" }), _jsx("input", { id: "cookie-path", className: "input", value: cookie.path, onChange: (e) => onChange({ ...cookie, path: e.target.value }) })] }), _jsxs("div", { className: "cookie-checkbox-row", children: [_jsxs("label", { className: "cookie-checkbox-label", children: [_jsx("input", { type: "checkbox", checked: cookie.secure, onChange: (e) => onChange({ ...cookie, secure: e.target.checked }) }), "Secure"] }), _jsxs("label", { className: "cookie-checkbox-label", children: [_jsx("input", { type: "checkbox", checked: cookie.httpOnly, onChange: (e) => onChange({ ...cookie, httpOnly: e.target.checked }) }), "HttpOnly"] })] }), _jsxs("div", { children: [_jsx("label", { htmlFor: "cookie-samesite", className: "small field-label", children: "SameSite" }), _jsxs("select", { id: "cookie-samesite", className: "input", value: cookie.sameSite, onChange: (e) => onChange({ ...cookie, sameSite: e.target.value }), children: [_jsx("option", { value: "Strict", children: "Strict" }), _jsx("option", { value: "Lax", children: "Lax" }), _jsx("option", { value: "None", children: "None" })] })] })] }), _jsxs("div", { className: "cookie-modal-actions", children: [_jsxs("button", { className: "btn flex-1", onClick: () => onSave(cookie), children: [_jsx(Save, { size: 16 }), " Save Cookie"] }), _jsx("button", { className: "btn btn-cancel", onClick: onClose, children: "Cancel" })] })] }) }));
}
