import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { BarChart, Bar, PieChart, Pie, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer, Cell, } from 'recharts';
import { chartTheme, chartTooltipStyle, axisTick } from './chart-theme';
export function DashboardCharts({ stats }) {
    const pieData = [
        { name: 'Succeeded', value: stats.succeeded_runs, color: chartTheme.success },
        { name: 'Failed', value: stats.failed_runs, color: chartTheme.error },
    ];
    return (_jsxs(_Fragment, { children: [_jsxs("div", { className: "dash-charts-row", children: [_jsxs("div", { className: "dash-chart-card", children: [_jsx("h2", { className: "dash-chart-title", children: "Success Rate" }), _jsx(ResponsiveContainer, { width: "100%", height: 280, children: _jsxs(PieChart, { children: [_jsx(Pie, { data: pieData, cx: "50%", cy: "50%", labelLine: false, label: (props) => `${props.name}: ${((props.percent ?? 0) * 100).toFixed(0)}%`, outerRadius: 80, fill: chartTheme.purple, dataKey: "value", children: pieData.map((entry, index) => (_jsx(Cell, { fill: entry.color }, `cell-${index}`))) }), _jsx(Tooltip, { contentStyle: chartTooltipStyle })] }) })] }), stats.runs_over_time && stats.runs_over_time.length > 0 && (_jsxs("div", { className: "dash-chart-card", children: [_jsx("h2", { className: "dash-chart-title", children: "Runs Over Time" }), _jsx(ResponsiveContainer, { width: "100%", height: 280, children: _jsxs(LineChart, { data: stats.runs_over_time, children: [_jsx(CartesianGrid, { strokeDasharray: "3 3", stroke: chartTheme.border }), _jsx(XAxis, { dataKey: "date", stroke: chartTheme.textDim, tick: axisTick }), _jsx(YAxis, { stroke: chartTheme.textDim, tick: axisTick }), _jsx(Tooltip, { contentStyle: chartTooltipStyle }), _jsx(Legend, { wrapperStyle: { color: chartTheme.textMuted } }), _jsx(Line, { type: "monotone", dataKey: "count", stroke: chartTheme.accent, strokeWidth: 2, dot: false })] }) })] }))] }), stats.runs_by_flow && stats.runs_by_flow.length > 0 && (_jsxs("div", { className: "dash-chart-card", children: [_jsx("h2", { className: "dash-chart-title", children: "Most Popular Flows" }), _jsx(ResponsiveContainer, { width: "100%", height: 280, children: _jsxs(BarChart, { data: stats.runs_by_flow.slice(0, 5), children: [_jsx(CartesianGrid, { strokeDasharray: "3 3", stroke: chartTheme.border }), _jsx(XAxis, { dataKey: "flow_name", stroke: chartTheme.textDim, tick: axisTick }), _jsx(YAxis, { stroke: chartTheme.textDim, tick: axisTick }), _jsx(Tooltip, { contentStyle: chartTooltipStyle }), _jsx(Legend, { wrapperStyle: { color: chartTheme.textMuted } }), _jsx(Bar, { dataKey: "count", fill: chartTheme.accent, radius: [4, 4, 0, 0] })] }) })] }))] }));
}
