import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Save } from 'lucide-react';
import { RECORDER_STYLES } from './FlowRecorder.types';
import { useFlowRecorder } from './useFlowRecorder';
import { RecorderUrlInput } from './RecorderUrlInput';
import { RecorderPreview } from './RecorderPreview';
import { RecorderStepList } from './RecorderStepList';
export function FlowRecorder({ onSaveFlow, onCancel }) {
    const recorder = useFlowRecorder(onSaveFlow);
    return (_jsxs("div", { className: "recorder-layout", children: [_jsxs("div", { className: "recorder-header", children: [_jsxs("div", { className: "h2 recorder-title", children: ["Flow Recorder", recorder.isRecording && _jsx("span", { className: "recorder-rec-badge", children: "REC" })] }), _jsxs("div", { className: "recorder-actions", children: [_jsx("button", { className: "btn recorder-btn-cancel", onClick: onCancel, children: "Cancel" }), _jsxs("button", { className: `btn recorder-btn-save ${recorder.recordedActions.length > 0 ? 'recorder-btn-save--active' : 'recorder-btn-save--disabled'}`, onClick: recorder.handleSave, disabled: recorder.recordedActions.length === 0, children: [_jsx(Save, { size: 14 }), " Save Flow"] })] })] }), recorder.error && _jsx("div", { className: "recorder-error", children: recorder.error }), _jsx(RecorderUrlInput, { targetUrl: recorder.targetUrl, setTargetUrl: recorder.setTargetUrl, isRecording: recorder.isRecording, flowName: recorder.flowName, setFlowName: recorder.setFlowName, mode: recorder.mode, availableModes: recorder.availableModes, cycleMode: recorder.cycleRecorderMode, modeStatusMessage: recorder.recorderStatusMessage, favoriteUrls: recorder.favoriteUrls, recentUrls: recorder.recentUrls, showUrlDropdown: recorder.showUrlDropdown, setShowUrlDropdown: recorder.setShowUrlDropdown, urlDropdownRef: recorder.urlDropdownRef, startRecording: recorder.startRecording, stopRecording: recorder.stopRecording, onToggleFavorite: recorder.handleToggleFavorite, onRemoveFavorite: recorder.handleRemoveFavorite, onRemoveRecent: recorder.handleRemoveRecent }), _jsxs("div", { className: "recorder-main", children: [_jsx(RecorderPreview, { targetUrl: recorder.targetUrl, isRecording: recorder.isRecording, mode: recorder.mode, iframeRef: recorder.iframeRef, iframeLoaded: recorder.iframeLoaded, showSubtitleOverlay: recorder.showSubtitleOverlay, activeStepIndex: recorder.activeStepIndex, recordedActions: recorder.recordedActions, onPopOut: recorder.popOutToWindow, serverScreenshot: recorder.serverScreenshot }), _jsx(RecorderStepList, { recordedActions: recorder.recordedActions, activeStepIndex: recorder.activeStepIndex, setActiveStepIndex: recorder.setActiveStepIndex, showSubtitleOverlay: recorder.showSubtitleOverlay, setShowSubtitleOverlay: recorder.setShowSubtitleOverlay, onRemoveAction: recorder.removeAction, onUpdateSubtitle: recorder.updateSubtitle, onClear: recorder.clearActions, onAddManual: recorder.addManualAction })] }), _jsx("style", { children: RECORDER_STYLES })] }));
}
