import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Trash2, TestTube, Check, Eye, EyeOff, ChevronDown, ChevronUp } from 'lucide-react';
import { getTypeInfo } from './integrations-types';
export function IntegrationCard({ integ, testing, expandedDeliveries, deliveries, onTest, onToggle, onDelete, onLoadDeliveries, }) {
    const info = getTypeInfo(integ.type);
    return (_jsxs("div", { children: [_jsxs("div", { className: `card integ-card${integ.enabled ? '' : ' integ-card--disabled'}`, children: [_jsx("div", { className: "integ-icon-box", children: info && _jsx(info.icon, { size: 20, style: { color: info.color } }) }), _jsxs("div", { className: "integ-meta", children: [_jsx("div", { className: "integ-name", children: integ.name }), _jsxs("div", { className: "integ-subtitle", children: [info?.label || integ.type, " \u00B7 ", integ.enabled ? 'Active' : 'Disabled'] })] }), _jsxs("div", { className: "integ-actions", children: [_jsx("button", { className: "btn integ-action-btn", onClick: () => onTest(integ.id), disabled: testing === integ.id, title: "Send test event", children: testing === integ.id ? (_jsx(Check, { size: 12, className: "integ-check-icon" })) : (_jsx(TestTube, { size: 12 })) }), _jsx("button", { className: "btn integ-action-btn", onClick: () => onLoadDeliveries(integ.id), title: "View delivery log", children: expandedDeliveries === integ.id ? _jsx(ChevronUp, { size: 12 }) : _jsx(ChevronDown, { size: 12 }) }), _jsx("button", { className: `btn integ-action-btn${integ.enabled ? '' : ' integ-action-btn--toggle-on'}`, onClick: () => onToggle(integ.id, !integ.enabled), children: integ.enabled ? _jsx(EyeOff, { size: 12 }) : _jsx(Eye, { size: 12 }) }), _jsx("button", { className: "btn integ-action-btn integ-action-btn--delete", onClick: () => onDelete(integ.id), children: _jsx(Trash2, { size: 12 }) })] })] }), expandedDeliveries === integ.id && _jsx(DeliveryLog, { deliveries: deliveries })] }));
}
function DeliveryLog({ deliveries }) {
    return (_jsx("div", { className: "delivery-log", children: deliveries.length === 0 ? (_jsx("div", { className: "delivery-empty", children: "No deliveries yet" })) : (deliveries.map((d) => (_jsxs("div", { className: "delivery-row", children: [_jsx("span", { className: d.success ? 'delivery-ok' : 'delivery-fail', children: d.success ? '\u2713' : '\u2717' }), _jsx("span", { className: "delivery-detail", children: d.event }), _jsxs("span", { className: "delivery-detail", children: ["HTTP ", d.status_code] }), _jsx("span", { className: "delivery-spacer" }), _jsx("span", { className: "delivery-time", children: new Date(d.attempted_at).toLocaleString() })] }, d.id)))) }));
}
