import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
export function JiraInstanceUrlField({ config, onChange }) {
    return (_jsxs("div", { className: "jira-field-group", children: [_jsx("label", { htmlFor: "jira-instance-url", className: "jira-label", children: "Jira Instance URL" }), _jsx("input", { id: "jira-instance-url", className: "input", type: "url", placeholder: "https://your-domain.atlassian.net", value: config.instanceUrl, onChange: (e) => onChange({ ...config, instanceUrl: e.target.value }), required: true }), _jsx("div", { className: "jira-hint", children: "Your Jira Cloud instance URL (e.g., https://company.atlassian.net)" })] }));
}
export function JiraCredentialsFields({ config, existingConfig, onChange }) {
    const [showSecret, setShowSecret] = useState(false);
    return (_jsxs("div", { className: "jira-grid-2col", children: [_jsxs("div", { children: [_jsx("label", { htmlFor: "jira-client-id", className: "jira-label", children: "Client ID" }), _jsx("input", { id: "jira-client-id", className: "input", type: "text", placeholder: "OAuth 2.0 Client ID", value: config.clientId, onChange: (e) => onChange({ ...config, clientId: e.target.value }), required: true })] }), _jsxs("div", { children: [_jsx("label", { htmlFor: "jira-client-secret", className: "jira-label", children: "Client Secret" }), _jsxs("div", { className: "jira-secret-wrapper", children: [_jsx("input", { id: "jira-client-secret", className: "input", type: showSecret ? 'text' : 'password', placeholder: "OAuth 2.0 Client Secret", value: config.clientSecret, onChange: (e) => onChange({ ...config, clientSecret: e.target.value }), required: !existingConfig, style: { paddingRight: 80 } }), _jsx("button", { type: "button", onClick: () => setShowSecret(!showSecret), className: "jira-show-toggle", children: showSecret ? 'Hide' : 'Show' })] })] })] }));
}
export function JiraProjectFields({ config, onChange }) {
    return (_jsxs("div", { className: "jira-grid-2col", children: [_jsxs("div", { children: [_jsx("label", { htmlFor: "jira-project-key", className: "jira-label", children: "Project Key" }), _jsx("input", { id: "jira-project-key", className: "input", type: "text", placeholder: "PROJ", value: config.projectKey, onChange: (e) => onChange({ ...config, projectKey: e.target.value.toUpperCase() }), required: true }), _jsx("div", { className: "jira-hint", children: "Jira project key (e.g., PROJ)" })] }), _jsxs("div", { children: [_jsx("label", { htmlFor: "jira-issue-type", className: "jira-label", children: "Default Issue Type" }), _jsx("input", { id: "jira-issue-type", className: "input", type: "text", placeholder: "Bug", value: config.issueType, onChange: (e) => onChange({ ...config, issueType: e.target.value }) }), _jsx("div", { className: "jira-hint", children: "Issue type for created issues" })] })] }));
}
export function JiraAutoCreateToggle({ config, onChange }) {
    return (_jsx("div", { className: "jira-auto-toggle", children: _jsxs("label", { className: "jira-auto-label", children: [_jsx("input", { type: "checkbox", checked: config.autoCreateOnFailure, onChange: (e) => onChange({ ...config, autoCreateOnFailure: e.target.checked }), style: { width: 16, height: 16 } }), _jsxs("div", { children: [_jsx("div", { className: "jira-auto-title", children: "Auto-create issues on failure" }), _jsx("div", { className: "jira-auto-desc", children: "Automatically create Jira issues when flows fail" })] })] }) }));
}
