import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Plus, ChevronLeft, ChevronRight, MessageSquare } from 'lucide-react';
import { StepItem } from './RecorderStepItem';
export function RecorderStepList(props) {
    const { recordedActions, activeStepIndex, setActiveStepIndex, showSubtitleOverlay, setShowSubtitleOverlay, onRemoveAction, onUpdateSubtitle, onClear, onAddManual, } = props;
    return (_jsxs("div", { className: "card rec-steplist-card", children: [_jsx(StepListHeader, { count: recordedActions.length, activeStepIndex: activeStepIndex, setActiveStepIndex: setActiveStepIndex, maxIndex: recordedActions.length - 1, showSubtitleOverlay: showSubtitleOverlay, setShowSubtitleOverlay: setShowSubtitleOverlay, onClear: onClear }), _jsx("div", { className: "rec-steplist-body", children: recordedActions.length === 0 ? (_jsxs("div", { className: "rec-steplist-empty", children: [_jsx(Plus, { size: 24, style: { marginBottom: 8, opacity: 0.5 } }), _jsx("div", { children: "No actions recorded yet" }), _jsx("div", { className: "rec-steplist-hint", children: "Interact with the page to record steps" })] })) : (_jsx("div", { className: "rec-steplist-items", children: recordedActions.map((action, idx) => (_jsx(StepItem, { action: action, index: idx, isActive: activeStepIndex === idx, onSelect: () => setActiveStepIndex(() => idx), onRemove: () => onRemoveAction(action.id), onSubtitleChange: (s) => onUpdateSubtitle(idx, s) }, action.id))) })) }), recordedActions.length > 0 && (_jsxs("div", { className: "rec-steplist-footer", children: [_jsx("div", { className: "rec-steplist-footer-label", children: "Quick Add:" }), _jsxs("div", { className: "rec-steplist-footer-actions", children: [_jsx("button", { className: "rec-quick-add-btn", onClick: () => onAddManual('click'), children: "+ Click" }), _jsx("button", { className: "rec-quick-add-btn", onClick: () => onAddManual('fill'), children: "+ Fill" })] })] }))] }));
}
function StepListHeader({ count, activeStepIndex, setActiveStepIndex, maxIndex, showSubtitleOverlay, setShowSubtitleOverlay, onClear, }) {
    return (_jsxs("div", { className: "rec-steplist-header", children: [_jsxs("span", { className: "rec-steplist-title", children: ["Recorded Steps (", count, ")"] }), _jsx("div", { className: "rec-steplist-nav", children: count > 0 && (_jsxs(_Fragment, { children: [_jsx("button", { className: "rec-nav-btn", onClick: () => setActiveStepIndex((i) => (i !== null && i > 0 ? i - 1 : i)), disabled: activeStepIndex === null || activeStepIndex <= 0, "aria-label": "Previous step", children: _jsx(ChevronLeft, { size: 14 }) }), _jsx("button", { className: "rec-nav-btn", onClick: () => setActiveStepIndex((i) => (i !== null && i < maxIndex ? i + 1 : i)), disabled: activeStepIndex === null || activeStepIndex >= maxIndex, "aria-label": "Next step", children: _jsx(ChevronRight, { size: 14 }) }), _jsx("button", { className: `rec-nav-btn${showSubtitleOverlay ? ' active' : ''}`, onClick: () => setShowSubtitleOverlay((v) => !v), "aria-label": showSubtitleOverlay ? 'Hide subtitles' : 'Show subtitles', "aria-pressed": showSubtitleOverlay, children: _jsx(MessageSquare, { size: 14 }) }), _jsx("button", { className: "rec-nav-btn rec-clear-btn", onClick: onClear, "aria-label": "Clear all steps", children: "Clear" })] })) })] }));
}
