import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Star, Clock, ExternalLink, Minimize2, Maximize2, Monitor, Play, Square, } from 'lucide-react';
import { getRecorderModeLabel, getRecorderModeTitle } from './recorder-runtime';
import { UrlDropdown } from './UrlDropdown';
export function RecorderUrlInput(props) {
    const { targetUrl, setTargetUrl, isRecording, flowName, setFlowName, mode, availableModes, cycleMode, modeStatusMessage, favoriteUrls, recentUrls, showUrlDropdown, setShowUrlDropdown, urlDropdownRef, startRecording, stopRecording, onToggleFavorite, onRemoveFavorite, onRemoveRecent, } = props;
    const isFav = favoriteUrls.includes(targetUrl);
    const hasDropdownItems = favoriteUrls.length > 0 || recentUrls.length > 0;
    return (_jsxs("div", { className: "card recorder-url-card", children: [_jsxs("div", { className: "recorder-url-row", children: [_jsxs("div", { ref: urlDropdownRef, className: "recorder-url-input-wrapper", children: [_jsx("input", { className: "input recorder-url-input", placeholder: "Enter URL to record (e.g., https://your-app.com)", value: targetUrl, onChange: (e) => setTargetUrl(e.target.value), disabled: isRecording, onKeyDown: (e) => e.key === 'Enter' && !isRecording && startRecording(), onFocus: () => !isRecording && setShowUrlDropdown(true) }), _jsxs("div", { className: "recorder-url-actions", children: [targetUrl && (_jsx("button", { onClick: () => onToggleFavorite(targetUrl), title: isFav ? 'Remove from favorites' : 'Add to favorites', className: `recorder-icon-btn ${isFav ? 'recorder-icon-fav-active' : 'recorder-icon-fav'}`, children: _jsx(Star, { size: 14, fill: isFav ? 'currentColor' : 'none' }) })), _jsx("button", { onClick: () => setShowUrlDropdown(!showUrlDropdown), disabled: isRecording, title: "Recent & favorite URLs", className: "recorder-icon-btn recorder-icon-muted", children: _jsx(Clock, { size: 14 }) })] }), showUrlDropdown && !isRecording && hasDropdownItems && (_jsx(UrlDropdown, { favoriteUrls: favoriteUrls, recentUrls: recentUrls, onSelect: (url) => {
                                    setTargetUrl(url);
                                    setShowUrlDropdown(false);
                                }, onRemoveFavorite: onRemoveFavorite, onRemoveRecent: onRemoveRecent }))] }), _jsx("button", { className: "btn recorder-mode-btn", onClick: cycleMode, disabled: isRecording || availableModes.length <= 1, title: getRecorderModeTitle(mode), children: mode === 'server' ? (_jsx(Monitor, { size: 14 })) : mode === 'iframe' ? (_jsx(Minimize2, { size: 14 })) : (_jsx(ExternalLink, { size: 14 })) }), !isRecording ? (_jsxs("button", { className: "btn recorder-start-btn", onClick: startRecording, children: [_jsx(Play, { size: 14 }), ' ', mode === 'server'
                                ? 'Record (Browser)'
                                : mode === 'window'
                                    ? 'Record in Window'
                                    : 'Start Recording'] })) : (_jsxs("button", { className: "btn recorder-stop-btn", onClick: stopRecording, children: [_jsx(Square, { size: 14 }), " Stop"] }))] }), _jsxs("div", { className: "recorder-name-row", children: [_jsx("input", { className: "input recorder-name-input", placeholder: "Flow name (e.g., 'User Login Flow')", value: flowName, onChange: (e) => setFlowName(e.target.value) }), _jsxs("div", { className: "recorder-mode-label", children: [mode === 'server' ? (_jsx(Monitor, { size: 11 })) : mode === 'iframe' ? (_jsx(Minimize2, { size: 11 })) : (_jsx(Maximize2, { size: 11 })), getRecorderModeLabel(mode)] })] }), _jsx("div", { className: "recorder-status-msg", children: modeStatusMessage })] }));
}
